import { Link } from 'react-router-dom';
import { Sparkles, Heart, Shield, Zap, ArrowRight, ChefHat, Activity, Target } from 'lucide-react';

export default function Home() {
  return (
    <div className="relative overflow-hidden">
      {/* Background Decorative Blobs */}
      <div className="absolute top-0 left-1/2 -translate-x-1/2 w-full h-[600px] bg-gradient-to-b from-emerald-50/50 to-transparent -z-10 pointer-events-none" />
      <div className="absolute top-20 -left-64 w-96 h-96 bg-emerald-300/20 rounded-full mix-blend-multiply filter blur-3xl opacity-70 animate-blob" />
      <div className="absolute top-40 -right-64 w-96 h-96 bg-teal-300/20 rounded-full mix-blend-multiply filter blur-3xl opacity-70 animate-blob animation-delay-2000" />

      {/* ── Hero Section ── */}
      <section className="relative pt-20 pb-32 text-center animate-fade-in z-10">
        <div className="inline-flex items-center gap-2 bg-white/60 backdrop-blur-md text-emerald-700 px-5 py-2.5 rounded-full text-sm font-semibold mb-8 border border-emerald-100 shadow-sm hover:shadow-md transition-shadow duration-300 cursor-default">
          <Sparkles className="w-4 h-4 text-amber-500" />
          The Future of Intelligent Nutrition
        </div>
        
        <h1 className="text-5xl sm:text-6xl lg:text-7xl font-extrabold text-slate-900 leading-[1.15] mb-6 tracking-tight">
          Design your diet with <br className="hidden sm:block" />
          <span className="text-transparent bg-clip-text bg-gradient-to-r from-emerald-500 via-teal-500 to-cyan-600 drop-shadow-sm">
            AI Precision
          </span>
        </h1>
        
        <p className="text-lg sm:text-xl text-slate-500 max-w-2xl mx-auto mb-10 leading-relaxed font-medium">
          Ditch the generic diets. Get a highly personalized, macro-balanced meal plan instantly generated by Google Gemini, complete with real recipes and cooking instructions.
        </p>
        
        <div className="flex flex-col sm:flex-row items-center justify-center gap-4 mb-16">
          <Link
            to="/dashboard"
            className="group relative inline-flex items-center gap-2 bg-slate-900 hover:bg-slate-800 text-white font-semibold py-4 px-9 rounded-2xl shadow-xl hover:shadow-2xl hover:-translate-y-1 transition-all duration-300 text-lg overflow-hidden w-full sm:w-auto justify-center"
          >
            <span className="absolute inset-0 w-full h-full bg-gradient-to-r from-emerald-500 to-teal-500 opacity-0 group-hover:opacity-100 transition-opacity duration-300" />
            <span className="relative flex items-center gap-2">
              Generate My Plan
              <ArrowRight className="w-5 h-5 group-hover:translate-x-1 transition-transform" />
            </span>
          </Link>
          
          <Link
            to="/login"
            className="inline-flex items-center gap-2 bg-white text-slate-700 hover:text-slate-900 font-semibold py-4 px-9 rounded-2xl border-2 border-slate-200 hover:border-slate-300 transition-all duration-300 text-lg w-full sm:w-auto justify-center"
          >
            Log In to Account
          </Link>
        </div>

        {/* Feature Highlights Grid */}
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 max-w-4xl mx-auto px-4">
          {[
            { icon: Zap, color: 'text-amber-500', bg: 'bg-amber-50', label: 'Instant Generation' },
            { icon: Target, color: 'text-rose-500', bg: 'bg-rose-50', label: 'Macro Targeted' },
            { icon: ChefHat, color: 'text-indigo-500', bg: 'bg-indigo-50', label: 'Real Recipes' },
            { icon: Activity, color: 'text-emerald-500', bg: 'bg-emerald-50', label: 'TDEE Accurate' },
          ].map((feature, i) => (
            <div key={i} className="glass-card rounded-2xl p-4 flex flex-col items-center gap-3 hover:-translate-y-1 transition-transform duration-300">
              <div className={`w-12 h-12 rounded-xl ${feature.bg} flex items-center justify-center`}>
                <feature.icon className={`w-6 h-6 ${feature.color}`} />
              </div>
              <span className="text-sm font-semibold text-slate-700">{feature.label}</span>
            </div>
          ))}
        </div>
      </section>

      {/* ── About Section ── */}
      <section className="relative py-24 bg-slate-50 border-t border-slate-100">
        <div className="container-app">
          <div className="flex flex-col lg:flex-row items-center gap-16">
            <div className="flex-1 lg:pr-8">
              <h2 className="text-3xl sm:text-4xl font-bold text-slate-900 mb-6 leading-tight">
                Nutrition Science meets <br />
                <span className="text-transparent bg-clip-text bg-gradient-to-r from-emerald-500 to-teal-500">Machine Intelligence</span>
              </h2>
              <p className="text-lg text-slate-600 leading-relaxed mb-6">
                Most diet apps just count your calories. NutriPlan AI actually creates the meals for you. 
                We use the scientifically-validated <strong className="text-slate-800">Mifflin-St Jeor equation</strong> to calculate your exact Total Daily Energy Expenditure (TDEE).
              </p>
              <p className="text-lg text-slate-600 leading-relaxed mb-8">
                Then, we instruct our LLM to scour thousands of culinary combinations to build a diet that fits your macros perfectly—without sacrificing taste or variety.
              </p>
              
              <ul className="space-y-4">
                {[
                  '100% personalized to your physical biometrics',
                  'Accounts for dietary restrictions (Vegan, Keto, etc.)',
                  'Generates step-by-step cooking instructions'
                ].map((item, i) => (
                  <li key={i} className="flex items-center gap-3 text-slate-700 font-medium">
                    <div className="w-6 h-6 rounded-full bg-emerald-100 flex items-center justify-center shrink-0">
                      <Shield className="w-3 h-3 text-emerald-600" />
                    </div>
                    {item}
                  </li>
                ))}
              </ul>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}
